use_frameworks!

target 'ETUtilities_Example' do
  pod 'ETUtilities', :path => '../'

  target 'ETUtilities_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 5.1.1'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
  
  target 'ETUtilities_UITests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 5.1.1'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end